// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectableLanguageDto } from "./DetectableLanguageDto";
import type { LanguageDetectionScopeSettingDto } from "./LanguageDetectionScopeSettingDto";

/**
 * Automatic source-language detection settings.
 */
export type AutoDetectionSettingsDto = { scope: LanguageDetectionScopeSettingDto, fallback_to: DetectableLanguageDto, };
