// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Clipboard format captured before normalization.
 */
export type ClipboardInputFormatDto = "plain_text" | "html";
