// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectableLanguageDto } from "./DetectableLanguageDto";

/**
 * Language-detection scope setting used by the Lingua detector.
 */
export type LanguageDetectionScopeSettingDto = "All" | "Common" | { "Custom": Array<DetectableLanguageDto> };
