// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Language-detection scope setting used by the Lingua detector.
 */
export type LanguageDetectionScopeSettingDto = "all" | "common" | "custom";
