// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Language-list scope for selectable translation languages.
 */
export type LanguageListScopeSettingDto = "all" | "common" | "custom";
