// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Language metadata shared with the frontend for display and translation choices.
 */
export type LanguageInfoDto = { name: string, code: string, };
