// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageInfoDto } from "./LanguageInfoDto";

/**
 * Language-list scope for selectable translation languages.
 */
export type LanguageListScopeSettingDto = "All" | "Common" | { "Custom": Array<LanguageInfoDto> };
