// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKindDto } from "./ProviderKindDto";

export type ModelSelectionDto = { provider: ProviderKindDto, id: string, };
