// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OllamaSettingsDto } from "./OllamaSettingsDto";

export type ProviderSettingsDto = { ollama: OllamaSettingsDto };
