// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipboardInputFormatDto } from "./ClipboardInputFormatDto";

/**
 * Clipboard input sent when quick-copy translation is triggered.
 */
export type QuickCopyTranslationInputDto = { text: string, format: ClipboardInputFormatDto, };
