// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageInfoDto } from "./LanguageInfoDto";

/**
 * Source language resolved during translation.
 */
export type ResolvedSourceLanguageDto = { "type": "detected" } & LanguageInfoDto | { "type": "assumed" } & LanguageInfoDto | { "type": "manual" } & LanguageInfoDto;
