// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageCodeDto } from "./LanguageCodeDto";

export type ResolvedSourceLanguageDto = { "type": "detected", code: LanguageCodeDto, } | { "type": "assumed", code: LanguageCodeDto, } | { "type": "manual", code: LanguageCodeDto, };
