// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppLocaleSettingDto } from "./AppLocaleSettingDto";
import type { AutoDetectionSettingsDto } from "./AutoDetectionSettingsDto";
import type { LanguageCodeDto } from "./LanguageCodeDto";
import type { LanguageListScopeSettingDto } from "./LanguageListScopeSettingDto";
import type { ModelSelectionDto } from "./ModelSelectionDto";
import type { ProviderSettingsDto } from "./ProviderSettingsDto";
import type { QuickCopyTranslateSettingsDto } from "./QuickCopyTranslateSettingsDto";
import type { SourceLanguageSettingDto } from "./SourceLanguageSettingDto";
import type { TargetLanguageSettingDto } from "./TargetLanguageSettingDto";
import type { ThemeSettingDto } from "./ThemeSettingDto";

export type SettingsDto = {
  theme: ThemeSettingDto;
  appLocale: AppLocaleSettingDto;
  quickCopyTranslate: QuickCopyTranslateSettingsDto;
  providers: ProviderSettingsDto;
  model: ModelSelectionDto | null;
  defaultSourceLanguage: SourceLanguageSettingDto;
  defaultTargetLanguage: TargetLanguageSettingDto;
  fallbackTargetLanguage: TargetLanguageSettingDto;
  languageListScope: LanguageListScopeSettingDto;
  customLanguageListScope: Array<LanguageCodeDto>;
  autoDetection: AutoDetectionSettingsDto;
  systemPrompt: string | null;
  translationPrompt: string;
};
