// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageCodeDto } from "./LanguageCodeDto";

/**
 * Source language selection sent with a translation request.
 */
export type SourceLanguageDto = { "type": "auto_detect" } | { "type": "manual", code: LanguageCodeDto, };
