// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageCodeDto } from "./LanguageCodeDto";

/**
 * Persisted default source language setting.
 */
export type SourceLanguageSettingDto = { "type": "auto_detect" } | { "type": "manual", code: LanguageCodeDto, };
