// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageCodeDto } from "./LanguageCodeDto";

/**
 * Persisted default target language setting.
 */
export type TargetLanguageSettingDto = LanguageCodeDto;
