// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Translation stream event sent to the frontend.
 */
export type TranslationStreamEventDto = { "type": "delta", requestId: number, fullText: string, } | { "type": "finished", requestId: number, fullText: string, } | { "type": "cancelled", requestId: number, } | { "type": "failed", requestId: number, message: string, };
