// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Translation stream event sent to the frontend.
 */
export type TranslationEventDto = { "type": "delta", request_id: number, full_text: string, } | { "type": "finished", request_id: number, full_text: string, };
