// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedSourceLanguageDto } from "./ResolvedSourceLanguageDto";

export type TranslationRequestResultDto = { resolvedSourceLanguage: ResolvedSourceLanguageDto, };
