// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKindDto } from "./ProviderKindDto";
import type { SourceLanguageDto } from "./SourceLanguageDto";
import type { TargetLanguageDto } from "./TargetLanguageDto";

export type TranslationRequestDto = {
  requestId: number;
  provider: ProviderKindDto;
  modelId: string;
  sourceLanguage: SourceLanguageDto;
  targetLanguage: TargetLanguageDto;
  text: string;
};
